services:
  postgres:
    image: ankane/pgvector
    environment:
      POSTGRES_DB: imdb_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
      image: redis
      ports:
        - "6379:6379"
volumes:
  pgdata: